server:
  port: 9090
#  error:
#    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/charvaq
    username: postgres
    password: 123

#  main:
#    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

#Swagger uchun
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    tryItOutEnabled: true
    path: swagger-ui
    csrf:
      enabled: true